# Generated by Django 4.2.30 on 2026-05-17 20:16

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('zone_type', models.CharField(choices=[('region', 'Région'), ('prefecture', 'Préfecture'), ('canton', 'Canton'), ('degraded', 'Zone dégradée')], max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='soils.administrativezone')),
            ],
            options={
                'verbose_name': 'Zone administrative',
                'verbose_name_plural': 'Zones administratives',
            },
        ),
        migrations.CreateModel(
            name='SoilPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('ph', models.FloatField(help_text='pH mesuré terrain', validators=[django.core.validators.MinValueValidator(3.5), django.core.validators.MaxValueValidator(9.5)])),
                ('humidity_pct', models.FloatField(help_text='Humidité %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('soil_type', models.CharField(choices=[('argileux', 'Argileux'), ('sableux', 'Sableux'), ('limoneux', 'Limoneux'), ('tourbeux', 'Tourbeux'), ('calcaire', 'Calcaire')], max_length=20)),
                ('fertility_class', models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée')], max_length=20)),
                ('fertility_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('photo', models.ImageField(blank=True, upload_to='soil_photos/%Y/%m/')),
                ('slope_pct', models.FloatField(blank=True, null=True)),
                ('ndvi_3m_avg', models.FloatField(blank=True, null=True)),
                ('smap_moisture_avg', models.FloatField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(default='terrain', max_length=100)),
                ('producer', models.CharField(blank=True, max_length=100)),
                ('collected_at', models.DateField()),
                ('is_validated', models.BooleanField(default=False)),
                ('quality_flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soil_points', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soil_points', to='soils.administrativezone')),
            ],
            options={
                'verbose_name': 'Point de sol',
                'verbose_name_plural': 'Points de sol',
            },
        ),
        migrations.CreateModel(
            name='SoilPointNasaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('observed_at', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('soil_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nasa_snapshots', to='soils.soilpoint')),
            ],
            options={
                'ordering': ['-observed_at'],
                'unique_together': {('soil_point', 'product', 'observed_at')},
            },
        ),
        migrations.AddIndex(
            model_name='soilpoint',
            index=models.Index(fields=['ph', 'soil_type'], name='soils_soilp_ph_0ae16a_idx'),
        ),
        migrations.AddIndex(
            model_name='soilpoint',
            index=models.Index(fields=['collected_at'], name='soils_soilp_collect_dc57eb_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativezone',
            index=models.Index(fields=['zone_type', 'code'], name='soils_admin_zone_ty_e8e0a2_idx'),
        ),
    ]
