# Generated by Django 4.2.30 on 2026-05-18 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilpoint',
            name='parent_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_points', to='soils.soilpoint'),
        ),
        migrations.AddField(
            model_name='soilpoint',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilpoint',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soilpoint',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SoilPointNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_notes', to=settings.AUTH_USER_MODEL)),
                ('soil_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_notes', to='soils.soilpoint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
