# Generated by Django 4.2.30 on 2026-05-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soils', '0002_soilpoint_parent_point_soilpoint_validated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soilpoint',
            options={'ordering': ['-collected_at', '-id'], 'verbose_name': 'Point de sol', 'verbose_name_plural': 'Points de sol'},
        ),
    ]
