# Generated by Django 4.2.30 on 2026-05-20 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sig_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(choices=[('auth', 'Authentification'), ('navigation', 'Navigation'), ('map', 'Carte'), ('parcel', 'Parcelles'), ('quiz', 'Quiz'), ('sheet', 'Fiches'), ('api', 'API'), ('tool', 'Outils'), ('other', 'Autre')], db_index=True, default='other', max_length=20)),
                ('view_name', models.CharField(blank=True, max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement activité',
                'verbose_name_plural': 'Événements activité',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='sig_platfor_user_id_4f8abd_idx'), models.Index(fields=['event_type', 'created_at'], name='sig_platfor_event_t_30429e_idx'), models.Index(fields=['session_id', 'created_at'], name='sig_platfor_session_09ec5e_idx'), models.Index(fields=['category', 'created_at'], name='sig_platfor_categor_00de83_idx')],
            },
        ),
    ]
