# Generated by Django 4.2.30 on 2026-05-17 20:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NasaLayerCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('MOD13Q1', 'MODIS NDVI/EVI'), ('SMAP', 'SMAP Soil Moisture'), ('GPM', 'GPM Precipitation'), ('SRTM', 'SRTM Elevation'), ('MOD16', 'MOD16 Evapotranspiration'), ('MOD11A2', 'MODIS Land Surface Temp'), ('ECOSTRESS', 'ECOSTRESS ET')], max_length=20)),
                ('layer_name', models.CharField(max_length=200)),
                ('acquisition_date', models.DateField()),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('raster_path', models.CharField(blank=True, max_length=500)),
                ('tile_url_template', models.CharField(blank=True, help_text='WMS/XYZ template for Leaflet overlay', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Couche NASA',
                'verbose_name_plural': 'Catalogue NASA',
                'ordering': ['-acquisition_date'],
                'indexes': [models.Index(fields=['product', 'acquisition_date'], name='nasa_nasala_product_ab9885_idx')],
            },
        ),
    ]
