# Generated by Django 4.2.30 on 2026-05-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilityModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(default='RandomForest', max_length=50)),
                ('sample_count', models.IntegerField()),
                ('f1_macro', models.FloatField(blank=True, null=True)),
                ('auc_roc', models.FloatField(blank=True, null=True)),
                ('feature_importance', models.JSONField(blank=True, default=dict)),
                ('confusion_matrix', models.JSONField(blank=True, default=dict)),
                ('model_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='FertilityPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_features', models.JSONField()),
                ('predicted_class', models.CharField(max_length=20)),
                ('predicted_score', models.FloatField()),
                ('recommendation', models.TextField()),
                ('inference_ms', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soil_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soils.soilpoint')),
            ],
        ),
    ]
