# Generated by Django 4.2.30 on 2026-05-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_category_comment_hidden'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videocomment',
            new_name='videos_vide_post_id_aa0e20_idx',
            old_name='videos_vide_post_id_cmt_idx',
        ),
        migrations.RenameIndex(
            model_name='videocomment',
            new_name='videos_vide_parent__7e0d5f_idx',
            old_name='videos_vide_parent_cmt_idx',
        ),
        migrations.RenameIndex(
            model_name='videopost',
            new_name='videos_vide_kind_c3434d_idx',
            old_name='videos_vide_kind_8a1f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='videopost',
            new_name='videos_vide_author__f5d040_idx',
            old_name='videos_vide_author_2c8e91_idx',
        ),
    ]
