# Generated by Django 4.2.30 on 2026-05-21 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0004_social_and_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='tags',
            field=models.CharField(blank=True, help_text='Hashtags séparés par des virgules (ex: sols,nasa)', max_length=500),
        ),
        migrations.CreateModel(
            name='StoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='stories/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
