# Generated by Django 4.2.30 on 2026-05-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userlocationhistory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='accounts_us_date_jo_ff39bb_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocationhistory',
            index=models.Index(fields=['recorded_at'], name='accounts_us_recorde_933f66_idx'),
        ),
    ]
