# Generated by Django 4.2.30 on 2026-05-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_age_user_city_user_consent_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_photos/%Y/%m/', verbose_name='Photo de profil'),
        ),
    ]
