# Generated by Django 4.2.30 on 2026-05-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='Courte présentation visible sur le profil et les commentaires', max_length=300, verbose_name='À propos'),
        ),
    ]
