# Generated by Django 4.2.30 on 2026-05-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', 'completed', 'started_at'], name='education_q_user_id_8344f3_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['completed', 'started_at'], name='education_q_complet_db4c26_idx'),
        ),
    ]
