# Generated by Django 4.2.30 on 2026-05-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_scale_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='exam_mode',
            field=models.BooleanField(default=False, help_text='Mode examen : pas de retour, timer global'),
        ),
    ]
